### ISSUE TITLE
Broken recently

### ISSUE THREAD

**Issue by marcfilleul** [flackr/scroll-timeline#183]
Hi,

I just checked websites where it was working correctly before and saw it wasn't working anymore.

Here are the console issues on Safari:

![CleanShot 2023-12-23 at 14 00 35@2x](https://github.com/flackr/scroll-timeline/assets/3406688/90a4b620-7b7f-423f-aaf0-da3256bbfc16)

And Firefox:

![CleanShot 2023-12-23 at 14 04 14@2x](https://github.com/flackr/scroll-timeline/assets/3406688/347b2edf-e842-4fbe-8d31-80e25628a5a3)

Looks like it could be cause by recent updates around proxy-animations.

Best regards

**Comment by bramus** [comment]
Thanks for reporting. Things seems to have gone wrong indeed …

The first error about `proxyAnimations` is an error that had gone unnoticed as it only triggers in strict mode. This happens when you load the script as via `type="module"`. I’ve got PR #184 up to fix this.

The second error is a bug introduced in #178, which broke the parsing of `animation-range` for ViewTimeline. I guess this went unnoticed as none of the demos actually uses an `animation-range`. I’ve got PR #185 up to fix that bug.

/cc @johannesodland @flackr

**Comment by bramus** [comment]
@marcfilleul The PRs I mentioned got merged. I believe these resolve the issues you reported. Can you confirm?

**Comment by flackr** [comment]
Thanks so much for the fixes @bramus

> The first error about `proxyAnimations` is an error that had gone unnoticed as it only triggers in strict mode. This happens when you load the script as via `type="module"`. I’ve got PR #184 up to fix this.

I filed #188 to ensure we test running the code in strict mode so this sort of thing should be caught.

> The second error is a bug introduced in #178, which broke the parsing of `animation-range` for ViewTimeline. I guess this went unnoticed as none of the demos actually uses an `animation-range`. I’ve got PR #185 up to fix that bug.

We're running all of the scroll-animation wpt tests too, I wonder if it's one that we fail for some other reason already which resulted in it not being caught.

**Comment by johannesodland** [comment]
> We're running all of the scroll-animation wpt tests too, I wonder if it's one that we fail for some other reason already which resulted in it not being caught.

I’ve got some time over the weekend. I’ll try to figure out which tests should have covered it, and see if we can get them to pass.

**Comment by marcfilleul** [comment]
> @marcfilleul The PRs I mentioned got merged. I believe these resolve the issues you reported. Can you confirm?

Indeed, it works now!
Thanks a lot 🥳
