### ISSUE TITLE
Incorrect handling negative values on Safari

### ISSUE THREAD

**Issue by zelenovsky** [flackr/scroll-timeline#281]
I currently use this code to init progress bar animation:
```js
element.animate(
    [{ width: "0" }, { width: "100%" }],
    {
        timeline: new ScrollTimeline({
            source: document.documentElement,
        }),
    },
);
```
It works perfect in V8, but is Safari when I scroll up from top of the page my progress bar appears with width: 100%. I suppose it is because of window.scrollY gets negative from top of the page, but in V8 it ends up at 0 always. Is there a way to fix it?

https://github.com/user-attachments/assets/eed3ad15-74de-4478-93a2-439baa30a8a0

**Comment by bramus** [comment]
Safari does something non-standard here and makes the scrolloffset negative when overscrolling, whereas other engines clamp it to 0.

Because of that, you can end up outside of the animation range where the animation is inactive.

To control what needs to be painted in that case, use the fill mode. Setting it to `"both"` should fix your problem.
